# fly.toml app configuration file generated for t3-live-chat2 on 2023-04-23T17:15:32+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "t3-live-chat2"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[http_service.ports]]
    handlers = ["http", "tls"]
    port = "3001"

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
